### ISSUE TITLE
Polymer build fails

### ISSUE THREAD

**Issue by web-devel** [cuba-platform/documentation#70]
```
module.js:549
    throw err;
    ^

Error: Cannot find module 'babel-core'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/work/platform-doc/polymer-build/node_modules/polymer-build/lib/optimize-streams.js:16:22)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
```

**Comment by web-devel** [comment]
https://github.com/Polymer/polymer-build/issues/305
